 export const meshProtoTypes = [
  ['Position',         7],
  ['User',          100],
  ['RouteDiscovery',100],
  ['Routing',100],
  ['Data',              9],
  ['KeyVerification',100],
  ['Waypoint',100],
  ['MqttClientProxyMessage',100],
  ['MeshPacket',        2],
  ['NodeInfo',          6],
  ['MyNodeInfo',        8],
  ['LogRecord',100],
  ['QueueStatus',100],
  ['FromRadio',         1],
  ['ClientNotification',100],
  ['KeyVerificationNumberInform',100],
  ['KeyVerificationNumberRequest',100],
  ['KeyVerificationFinal',100],
  ['DuplicatedPublicKey',100],
  ['LowEntropyKey',100],
  ['FileInfo',100],
  ['ToRadio',           3],
  ['Compressed',100],
  ['NeighborInfo',100],
  ['Neighbor',100],
  ['DeviceMetadata',100],
  ['Heartbeat',100],
  ['NodeRemoteHardwarePin',100],
  ['ChunkedPayload',100],
  ['resend_chunks',100],
  ['ChunkedPayloadResponse',100],
  ['ChannelSettings',100],
  ['ModuleSettings',100],
  ['Channel',100],
  ['Config',            4],
  ['DeviceUIConfig',100],
  ['NodeFilter',100],
  ['NodeHighlight',100],
  ['GeoPoint',100],
  ['Map',100],
  ['ModuleConfig',      5],
  ['RemoteHardwarePin',100],
  ['DeviceMetrics',100],
  ['EnvironmentMetrics',100],
  ['PowerMetrics',100],
  ['AirQualityMetrics',100],
  ['LocalStats',100],
  ['HealthMetrics',100],
  ['HostMetrics',100],
  ['Telemetry',100],
  ['Nau781002Config',100],
  ['XModem',100],
]

export function sortEntries (entries) {
   return entries.sort((a, b) => a[1] - b[1]).map(([key, _]) => key);
}
